server:
  port: 8080
  servlet:
    context-path: /
    
springdoc:
  api-docs:
    path: "/api/specs/openapi"
  swagger-ui:
    enabled: true
    path: "/api/docs"
    displayRequestDuration: true
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

logging:
  level:
    root: INFO
    org:
      springframework: WARN