server:
  port: 8080
  servlet:
    context-path: /
    
management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org:
      springframework: WARN